server:
  port: 80
spring:
  application:
    name: lbt-user
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      username: Imu
#      password: Imu.123456
#      url: jdbc:mysql://192.168.9.147:3306/imu_purse?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&rewriteBatchedStatements=TRUE
#      driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.wwb: debug


#熔断器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000



