server:
  port: 9006
logging:
  level:
    com.wwb: info

#熔断器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

